version: '3'
services:
  db:
    image:  postgres:11
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:  youla_parser_root
      POSTGRES_PASSWORD:  youla_parser_secret
      POSTGRES_DB: youla_parser